### ISSUE TITLE
'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by jpcodr** [legastero/stanza#345]
I use stanza in Web and Cordova and use browserify as bundler with babelify transformer.
I've updated to `stanza@11.3.2` from `stanza.io@9.2.0` and now i can't build my js file.

The task on `gulpfile.babel.js` :
```js
function buildJsApp () {
    return browserify({
        entries: [ 'src/js/index.es6.js' ],
        extensions: [ '.es6.js' ],
	transform: [ babelify ],
	debug: true
    })
    .external(vendors)
    .bundle()
    .on('error', handleError)
    .pipe(source('app.js'))
    .pipe(gulp.dest('www/js/'))
}
```
The `.babelrc` file
```json
{
    "presets": [
        "@babel/preset-env"
    ]
}
```
The Error:
```
{ SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0) while parsing /Users/jpablom/devel/sonderJS/node_modules/stanza/browser-module.js while parsing file: /Users/jpablom/devel/sonderJS/node_modules/stanza/browser-module.js
    at DestroyableTransform.end [as _flush] (/Users/jpablom/devel/sonderMobile/app/node_modules/insert-module-globals/index.js:114:21)
    at DestroyableTransform.prefinish (/Users/jpablom/devel/sonderMobile/app/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)
    at prefinish (/Users/jpablom/devel/sonderMobile/app/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/Users/jpablom/devel/sonderMobile/app/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/Users/jpablom/devel/sonderMobile/app/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/Users/jpablom/devel/sonderMobile/app/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DestroyableTransform.onend (/Users/jpablom/devel/sonderMobile/app/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at DestroyableTransform.emit (events.js:208:7)
    at endReadableNT (/Users/jpablom/devel/sonderMobile/app/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  type: 'syntax',
...
```

With `stanza.io@9.2.0` works as expected.

Am i missing something?
Thanks

**Comment by jpablom** [comment]
@legastero something about this???
